#############################################################################
# Makefile for building: pairs_gui.app/Contents/MacOS/pairs_gui
# Generated by qmake (3.1) (Qt 6.2.1)
# Project:  pairs_gui.pro
# Template: app
# Command: /Users/anhpham/Qt/6.2.1/macos/bin/qmake -o Makefile pairs_gui.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.14 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.14 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers -I/Users/anhpham/Qt/6.2.1/macos/lib/QtGui.framework/Headers -I/Users/anhpham/Qt/6.2.1/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers/ -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers/ -I/Users/anhpham/Qt/6.2.1/macos/mkspecs/macx-clang -F/Users/anhpham/Qt/6.2.1/macos/lib
QMAKE         = /Users/anhpham/Qt/6.2.1/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/anhpham/Qt/6.2.1/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/anhpham/Qt/6.2.1/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = pairs_gui1.0.0
DISTDIR = /Users/anhpham/Desktop/HW_Materials/Old\ course/COMP.CS.110/student/13/pairs_gui/.tmp/pairs_gui1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.14 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/anhpham/Qt/6.2.1/macos/lib
LIBS          = $(SUBLIBS) -F/Users/anhpham/Qt/6.2.1/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework AGL -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = game.cpp \
		main.cpp \
		mainwindow.cpp qrc_mainwindow.cpp \
		moc_game.cpp \
		moc_mainwindow.cpp
OBJECTS       = game.o \
		main.o \
		mainwindow.o \
		qrc_mainwindow.o \
		moc_game.o \
		moc_mainwindow.o
DIST          = /Users/anhpham/Qt/6.2.1/macos/mkspecs/features/spec_pre.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/device_config.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/unix.conf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/mac.conf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/macx.conf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/sanitize.conf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/gcc-base.conf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/gcc-base-mac.conf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/clang.conf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/clang-mac.conf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/qconfig.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_ext_freetype.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_ext_libpng.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_core.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_core_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_dbus.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_designer.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_gui.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_help.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_help_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labssettings.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_linguist.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_network.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_network_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_opengl.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qml.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quick.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_sql.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_svg.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_testlib.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_tools_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_uitools.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_widgets.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_xml.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/qt_functions.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/qt_config.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/macx-clang/qmake.conf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/exclusive_builds.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/sdk.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/toolchain.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/toolchain.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/default_pre.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/default_pre.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/resolve_config.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/default_post.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/default_post.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/objective_c.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/qml_debug.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/mac.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/warn_on.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/qt.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/resources_functions.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/resources.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/moc.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/unix/opengl.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/uic.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/unix/thread.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/qmake_use.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/file_copies.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/rez.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/asset_catalogs.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/testcase_targets.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/exceptions.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/yacc.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/lex.prf \
		pairs_gui.pro game.hh \
		mainwindow.hh game.cpp \
		main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = pairs_gui
DESTDIR       = 
TARGET        = pairs_gui.app/Contents/MacOS/pairs_gui

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15.6
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/anhpham/Desktop/HW_Materials/Old course/COMP.CS.110/student/13/pairs_gui/.qmake.stash
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = x86_64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/anhpham/Desktop/HW_Materials/Old course/COMP.CS.110/student/13/pairs_gui/pairs_gui.pro


include /Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

pairs_gui.app/Contents/MacOS/pairs_gui: ui_game.h ui_mainwindow.h $(OBJECTS)  
	@test -d pairs_gui.app/Contents/MacOS/ || mkdir -p pairs_gui.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pairs_gui.pro /Users/anhpham/Qt/6.2.1/macos/mkspecs/macx-clang/qmake.conf /Users/anhpham/Qt/6.2.1/macos/mkspecs/features/spec_pre.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/device_config.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/unix.conf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/mac.conf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/macx.conf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/sanitize.conf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/gcc-base.conf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/gcc-base-mac.conf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/clang.conf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/clang-mac.conf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/qconfig.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_ext_freetype.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_ext_libpng.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_core.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_core_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_dbus.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_designer.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_gui.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_help.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_help_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labssettings.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_linguist.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_network.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_network_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_opengl.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qml.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quick.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_sql.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_svg.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_testlib.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_tools_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_uitools.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_widgets.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_xml.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/qt_functions.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/qt_config.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/macx-clang/qmake.conf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/exclusive_builds.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/sdk.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/toolchain.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/toolchain.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/default_pre.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/default_pre.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/resolve_config.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/default_post.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/default_post.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/objective_c.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/qml_debug.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/mac.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/warn_on.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/qt.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/resources_functions.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/resources.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/moc.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/unix/opengl.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/uic.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/unix/thread.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/qmake_use.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/file_copies.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/rez.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/asset_catalogs.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/testcase_targets.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/exceptions.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/yacc.prf \
		/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/lex.prf \
		pairs_gui.pro \
		mainwindow.qrc \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtGui.framework/Resources/QtGui.prl \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile pairs_gui.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/spec_pre.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/device_config.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/unix.conf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/mac.conf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/macx.conf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/sanitize.conf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/gcc-base.conf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/gcc-base-mac.conf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/clang.conf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/common/clang-mac.conf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/qconfig.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_ext_freetype.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_ext_libpng.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_concurrent.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_core.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_core_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_dbus.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_designer.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_designer_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_gui.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_gui_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_help.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_help_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labsanimation.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labssettings.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_linguist.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_linguist_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_network.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_network_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_opengl.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_printsupport.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qml.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qml_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlcore.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmltest.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quick.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quick_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_sql.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_sql_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_svg.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_svg_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_testlib.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_tools_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_uitools.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_widgets.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_xml.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/modules/qt_lib_xml_private.pri:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/qt_functions.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/qt_config.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/macx-clang/qmake.conf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/exclusive_builds.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/sdk.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/toolchain.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/toolchain.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/default_pre.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/default_pre.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/resolve_config.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/default_post.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/default_post.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/objective_c.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/qml_debug.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/mac.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/warn_on.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/qt.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/resources_functions.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/resources.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/moc.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/unix/opengl.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/uic.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/unix/thread.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/qmake_use.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/file_copies.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/rez.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/mac/asset_catalogs.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/testcase_targets.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/exceptions.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/yacc.prf:
/Users/anhpham/Qt/6.2.1/macos/mkspecs/features/lex.prf:
pairs_gui.pro:
mainwindow.qrc:
/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/Users/anhpham/Qt/6.2.1/macos/lib/QtGui.framework/Resources/QtGui.prl:
/Users/anhpham/Qt/6.2.1/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile pairs_gui.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

pairs_gui.app/Contents/PkgInfo: 
	@test -d pairs_gui.app/Contents || mkdir -p pairs_gui.app/Contents
	@$(DEL_FILE) pairs_gui.app/Contents/PkgInfo
	@echo "APPL????" > pairs_gui.app/Contents/PkgInfo
pairs_gui.app/Contents/Resources/empty.lproj: 
	@test -d pairs_gui.app/Contents/Resources || mkdir -p pairs_gui.app/Contents/Resources
	@touch pairs_gui.app/Contents/Resources/empty.lproj
	
pairs_gui.app/Contents/Info.plist: 
	@test -d pairs_gui.app/Contents || mkdir -p pairs_gui.app/Contents
	@$(DEL_FILE) pairs_gui.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,123.pairs-gui,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},123.pairs-gui,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.14,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,pairs_gui,g" -e "s,@LIBRARY@,pairs_gui,g" -e "s,\$${EXECUTABLE_NAME},pairs_gui,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /Users/anhpham/Qt/6.2.1/macos/mkspecs/macx-clang/Info.plist.app >pairs_gui.app/Contents/Info.plist

all: Makefile \
		pairs_gui.app/Contents/PkgInfo \
		pairs_gui.app/Contents/Resources/empty.lproj \
		pairs_gui.app/Contents/Info.plist pairs_gui.app/Contents/MacOS/pairs_gui

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.qrc $(DISTDIR)/
	$(COPY_FILE) --parents game.hh mainwindow.hh $(DISTDIR)/
	$(COPY_FILE) --parents game.cpp main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents game.ui mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r pairs_gui.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_mainwindow.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_mainwindow.cpp
qrc_mainwindow.cpp: mainwindow.qrc \
		/Users/anhpham/Qt/6.2.1/macos/libexec/rcc \
		Resources/bananas.png \
		Resources/mango.png \
		Resources/mangtosteen.png \
		Resources/jackfruit.png \
		Resources/found.png \
		Resources/eggplant.png \
		Resources/watermelon.png \
		Resources/pear.png \
		Resources/starfruit.png \
		Resources/apple.png \
		Resources/coconut.png \
		Resources/cucumber.png \
		Resources/lemon.png \
		Resources/pineapple.png \
		Resources/tomato.png \
		Resources/cherries.png \
		Resources/question.png \
		Resources/lychee.png \
		Resources/strawberry.png \
		Resources/orange.png \
		Resources/grapes.png \
		Resources/kiwi.png
	/Users/anhpham/Qt/6.2.1/macos/libexec/rcc -name mainwindow mainwindow.qrc -o qrc_mainwindow.cpp

compiler_moc_header_make_all: moc_game.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_game.cpp moc_mainwindow.cpp
moc_game.cpp: game.hh \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/QDialog \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		/Users/anhpham/Qt/6.2.1/macos/libexec/moc
	/Users/anhpham/Qt/6.2.1/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=12 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/anhpham/Qt/6.2.1/macos/mkspecs/macx-clang -I'/Users/anhpham/Desktop/HW_Materials/Old course/COMP.CS.110/student/13/pairs_gui' -I/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers -I/Users/anhpham/Qt/6.2.1/macos/lib/QtGui.framework/Headers -I/Users/anhpham/Qt/6.2.1/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/anhpham/Qt/6.2.1/macos/lib game.hh -o moc_game.cpp

moc_mainwindow.cpp: mainwindow.hh \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtCore.framework/Headers/QString \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtCore.framework/Headers/qstring.h \
		game.hh \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/QDialog \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/QGridLayout \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtGui.framework/Headers/QPixmap \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtGui.framework/Headers/qpixmap.h \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/QPushButton \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/Users/anhpham/Qt/6.2.1/macos/libexec/moc
	/Users/anhpham/Qt/6.2.1/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=12 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/anhpham/Qt/6.2.1/macos/mkspecs/macx-clang -I'/Users/anhpham/Desktop/HW_Materials/Old course/COMP.CS.110/student/13/pairs_gui' -I/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers -I/Users/anhpham/Qt/6.2.1/macos/lib/QtGui.framework/Headers -I/Users/anhpham/Qt/6.2.1/macos/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/anhpham/Qt/6.2.1/macos/lib mainwindow.hh -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_game.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_game.h ui_mainwindow.h
ui_game.h: game.ui \
		/Users/anhpham/Qt/6.2.1/macos/libexec/uic
	/Users/anhpham/Qt/6.2.1/macos/libexec/uic game.ui -o ui_game.h

ui_mainwindow.h: mainwindow.ui \
		/Users/anhpham/Qt/6.2.1/macos/libexec/uic
	/Users/anhpham/Qt/6.2.1/macos/libexec/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

game.o: game.cpp game.hh \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/QDialog \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_game.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game.o game.cpp

main.o: main.cpp mainwindow.hh \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtCore.framework/Headers/QString \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtCore.framework/Headers/qstring.h \
		game.hh \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/QDialog \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/QGridLayout \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtGui.framework/Headers/QPixmap \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtGui.framework/Headers/qpixmap.h \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/QPushButton \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/QApplication \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.hh \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtCore.framework/Headers/QString \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtCore.framework/Headers/qstring.h \
		game.hh \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/QDialog \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/qdialog.h \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/QGridLayout \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtGui.framework/Headers/QPixmap \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtGui.framework/Headers/qpixmap.h \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/QPushButton \
		/Users/anhpham/Qt/6.2.1/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qrc_mainwindow.o: qrc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_mainwindow.o qrc_mainwindow.cpp

moc_game.o: moc_game.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_game.o moc_game.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/pairs_gui/bin || mkdir -p $(INSTALL_ROOT)/opt/pairs_gui/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/pairs_gui/bin/pairs_gui.app
	
	$(QINSTALL) pairs_gui.app $(INSTALL_ROOT)/opt/pairs_gui/bin/pairs_gui.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/pairs_gui/bin/pairs_gui.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/pairs_gui/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

